#!/usr/bin/env python3
"""Generate the specification appendices from the YAML source of truth.

    python3 lib/build_appendix.py            # write spec/appendix-a.md and friends
    python3 lib/build_appendix.py --check    # fail if the files are out of date

`spec/wordlist.yaml` and `spec/terms.yaml` are the only places to edit vocabulary.
The appendices are generated, so the standard and the checker can never disagree
about which words are approved.

The same `--check` run also regenerates `spec/rule_weights.csv` from the weight
table in PSTE-1.md §15.5. That table, not the CSV, is where a person edits a
weight: spec/PSTE-1.md is normative text, and the CSV exists only so a program can
read the weights without parsing markdown. Generating the CSV from the table is
what keeps the two from disagreeing, the same reason the word appendices are
generated from the YAML files rather than hand-written.
"""

import argparse
import csv
import io
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "spec")
sys.path.insert(0, os.path.join(ROOT, "evals"))

import pste_lint  # noqa: E402

HEADER = "<!-- Generated by lib/build_appendix.py. Edit spec/*.yaml instead. -->\n"


def parse_entries(path):
    """Read the word entries with their fields, preserving order.

    Uses the same tolerant reader as the checker rather than a YAML library, so the
    two tools cannot disagree about what the file says.
    """
    entries, current, section = [], None, None
    pending_key = None
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = pste_lint._strip_comment(raw)
            if not line.strip():
                continue
            indent = len(line) - len(line.lstrip())
            s = line.strip()

            if indent == 0 and s.endswith(":"):
                section = s[:-1]
                if current:
                    entries.append(current)
                    current = None
                continue
            if section != "words":
                continue

            if s.startswith("- word:"):
                if current:
                    entries.append(current)
                current = {"word": pste_lint._unquote(s.split(":", 1)[1])}
                pending_key = None
            elif current is not None and ":" in s and not s.startswith("- "):
                key, rest = s.split(":", 1)
                key, rest = key.strip(), rest.strip()
                if rest.startswith("["):
                    current[key] = pste_lint._flow_list(rest)
                    pending_key = None
                elif rest in (">", "|"):
                    current[key] = ""
                    pending_key = key
                elif rest:
                    current[key] = pste_lint._unquote(rest)
                    pending_key = None
                else:
                    current[key] = []
                    pending_key = key
            elif current is not None and s.startswith("- ") and pending_key:
                current.setdefault(pending_key, [])
                if isinstance(current[pending_key], list):
                    current[pending_key].append(pste_lint._unquote(s[2:]))
            elif current is not None and pending_key and isinstance(
                current.get(pending_key), str
            ):
                current[pending_key] = (current[pending_key] + " " + s).strip()
    if current:
        entries.append(current)
    return [e for e in entries if e.get("word") and e["word"] != "null"]


def appendix_a(entries):
    out = [
        HEADER,
        "# Appendix A — Approved words (normative)\n",
        "Each word has one approved meaning and one approved part of speech "
        "(PSTE-V2).\n",
        "A word that this list does not name is not thereby forbidden while the list "
        "is incomplete. See `METHOD.md`.\n",
        "| Word | Part of speech | Approved meaning | Use instead of |",
        "|---|---|---|---|",
    ]
    for e in sorted(entries, key=lambda x: (x["word"], x.get("pos", ""))):
        instead = ", ".join(e.get("instead_of", []) or [])
        meaning = (e.get("meaning") or "").replace("|", "\\|")
        out.append(
            f"| `{e['word']}` | {e.get('pos', '')} | {meaning} | "
            f"{instead or '—'} |"
        )
    out.append(f"\n{len(entries)} approved entries.\n")
    return "\n".join(out)


def appendix_c(entries):
    routed = {}
    for e in entries:
        for bad in e.get("instead_of", []) or []:
            routed.setdefault(bad.lower(), []).append(e["word"])
    out = [
        HEADER,
        "# Appendix C — Words to avoid (informative)\n",
        "Each entry names the approved word to use in its place. A word with no "
        "replacement carries no information: delete it.\n",
        "| Avoid | Use instead |",
        "|---|---|",
    ]
    for bad in sorted(routed):
        targets = ", ".join(f"`{t}`" for t in sorted(set(routed[bad])))
        out.append(f"| {bad} | {targets} |")
    out.append(f"\n{len(routed)} entries.\n")

    # PSTE-L5 frames. These are phrases and not words, and they have no replacement,
    # so they need their own table rather than a row in the one above. `load_vocab`
    # already reads them, so this does not add a second parser for the same file.
    frames = sorted(pste_lint.load_vocab().get("frames", []))
    if frames:
        out += [
            "\n## C.1 Frame phrases (PSTE-L5)\n",
            "A frame announces or closes a response and states no fact. Delete it. "
            "These are findings at the start or the end of a text only. The same "
            "words inside a text can carry meaning.\n",
            "| Frame |",
            "|---|",
        ]
        out += [f"| {f} |" for f in frames]
        out.append(f"\n{len(frames)} phrases.\n")
    return "\n".join(out)


WEIGHT_ROW_RE = re.compile(
    r"^\|\s*(PSTE-[A-Z0-9.]+)\s*\|\s*([0-9.]+|N/A)\s*\|\s*(.*?)\s*\|$"
)


def parse_weight_table(path):
    """Read the §15.5 weight table straight out of PSTE-1.md.

    The table is the normative source. This walks the raw markdown rather than a
    general table parser, the same tolerant-reader approach `parse_entries` above
    takes for the YAML files, so this script never needs a markdown library.
    """
    rows = []
    in_table = False
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.strip() == "### 15.5 The weight table":
                in_table = True
                continue
            if in_table and line.startswith("### "):
                break
            if not in_table:
                continue
            m = WEIGHT_ROW_RE.match(line.strip())
            if m:
                rows.append(m.groups())
    return rows


def rule_weights_csv(rows):
    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(["rule", "weight", "reason"])
    writer.writerows(rows)
    return buf.getvalue()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    entries = parse_entries(os.path.join(SPEC, "wordlist.yaml"))
    weight_rows = parse_weight_table(os.path.join(SPEC, "PSTE-1.md"))
    files = {
        "appendix-a.md": appendix_a(entries),
        "appendix-c.md": appendix_c(entries),
        "rule_weights.csv": rule_weights_csv(weight_rows),
    }

    stale = []
    for name, body in files.items():
        path = os.path.join(SPEC, name)
        old = ""
        if os.path.exists(path):
            with open(path, encoding="utf-8") as fh:
                old = fh.read()
        if old == body:
            continue
        if args.check:
            stale.append(name)
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(body)
            print(f"wrote spec/{name}")

    if args.check and stale:
        print(
            "out of date: " + ", ".join(stale) + "\nrun: python3 lib/build_appendix.py",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("appendices are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
